name: CI

on:
  pull_request:

jobs:
  sync-dependent-files:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.auto-commit-action.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Sync dependent files
        run: ./tools/sync-dependencies.sh
      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4.15.4

  check:
    needs: sync-dependent-files
    strategy:
      matrix:
        platform:
          - macos-latest
          - ubuntu-latest
    name: check - (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.sync-dependent-files.outputs.commit_hash || github.head_ref }}

      - name: Install bazelisk
        run: ./tools/ci/install_bazelisk.sh v1.15.0 ${{ matrix.platform }}

      - name: Test
        id: test
        run: ./bin/bazel test //...
      
      # Required for https://github.com/stefanzweifel/git-auto-commit-action/issues/231
      - name: Update job status
        if: ${{ always() }}
        run: |
          curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/`git rev-parse HEAD` \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "context": "CI / check - (${{ matrix.platform }}) (pull_request)",
              "state": "${{ steps.test.result }}",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }'
